# Generated by Django 5.0.1 on 2024-01-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisrapp', '0002_transaction_computable_alter_transaction_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_datetime', models.DateTimeField(auto_now_add=True)),
                ('new_rows', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'sincronización',
                'verbose_name_plural': 'sincronizaciones',
                'ordering': ['-sync_datetime'],
            },
        ),
        migrations.AlterModelOptions(
            name='usertoken',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='usertoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2020-07-10T00:00:00Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='TransaccionProgramada',
        ),
    ]
